[workspace]
members = [
    "meilisearch-core",
    "meilisearch-http",
    "meilisearch-raft",
    "meilisearch-schema",
    "meilisearch-tokenizer",
    "meilisearch-types",
]

[profile.release]
debug = true
