[package]
name = "meilisearch-raft"
version = "0.1.0"
authors = ["Quentin de Quelen <quentin@dequelen.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-raft = "0.4.2"
serde = "1.0.103"
actix = "0.8.3"

[dev-dependencies]
structopt = "0.3.2"
rustyline = "5.0.5"
